# Generated by Django 5.2.3 on 2025-12-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='recieved', max_length=100),
        ),
    ]
