# Generated by Django 5.2.3 on 2026-01-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_manager', '0002_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='forward',
            field=models.BooleanField(default=False),
        ),
    ]
