# Generated by Django 5.2.3 on 2025-12-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupRecord',
        ),
    ]
