# Generated by Django 5.2.3 on 2025-12-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosalert',
            name='user',
        ),
        migrations.AddField(
            model_name='sosalert',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
