# Generated by Django 5.2.3 on 2025-12-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_sosalert_user_sosalert_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
