# Generated by Django 5.2.3 on 2025-12-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sosalert_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
