# Generated by Django 5.2.3 on 2025-12-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprecord',
            name='role',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
