# Generated by Django 5.2.3 on 2025-12-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_signuprecord_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='username',
            field=models.CharField(default='dummy', max_length=100),
        ),
        migrations.AlterField(
            model_name='signuprecord',
            name='role',
            field=models.CharField(default='user', max_length=150, null=True),
        ),
    ]
