# Generated by Django 5.2.6 on 2025-12-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_signuprecord_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprecord',
            name='role',
            field=models.CharField(default='user', max_length=150, null=True),
        ),
    ]
