# Generated by Django 5.2.3 on 2025-12-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_complaint_username_alter_signuprecord_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
