# Generated by Django 5.2.6 on 2025-12-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_signuprecord_role'),
        ('user', '0004_alter_complaint_username'),
    ]

    operations = [
    ]
