# Generated by Django 5.2.3 on 2025-12-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20251226_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='district',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
