# Generated by Django 5.2.3 on 2025-12-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_complaint_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprecord',
            name='district',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
